Assistant checkpoint: Fix Git SSH dependency issue for deployment
Assistant generated file changes:
- package.json: Change libsignal dependency from SSH to HTTPS URL
Change libsignal dependency from SSH to HTTPS URL
Ensure libsignal uses HTTPS Git URL
- .yarnrc: Force Yarn to use HTTPS for Git repositories

---

User prompt:

sha256:f4aee9e53c42a22ed82451218c3ea03d1eea8d6ca8fbe8eb4e950304ba8a8bb3
Copying blob sha256:b336e209998fa5cf0eec3dabf93a21194198a35f4f75612d8da03693f8c30217
Copying blob sha256:e177a2ca3fa6c1a8ba72135dbd758214b9fbb9d3f49eff63cf18349a22f00456
Copying blob sha256:ea4ec23266a3af1204fd643de0f3572dd8dbb5697a5ef15bdae844777c19bf8f
Copying config sha256:456f7446368b903f920a982cf669f07aefc874b81ca986fb9e514c1285a98e2f
Writing manifest to image destination
Warning: PACK_VOLUME_KEY is unset; set this environment variable to a secret value to avoid creating a new volume cache on every build
===> ANALYZING
[analyzer] Image with name "imageblueprint" not found
===> DETECTING
[detector] Timer: Detector started at 2025-09-11T16:41:26Z
[detector] 3 of 5 buildpacks participating
[detector] google.nodejs.runtime    1.0.0
[detector] google.nodejs.yarn       2.1.0
[detector] google.utils.label-image 0.0.2
[detector] Timer: Detector ran for 460.12181ms and ended at 2025-09-11T16:41:27Z
===> RESTORING
time="2025-09-11T16:41:32Z" level=warning msg="IdleTracker: StateClosed transition by connection marked un-managed" X-Reference-Id=0xc000718408
===> BUILDING
[builder] Timer: Builder started at 2025-09-11T16:41:34Z
[builder] === Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
[builder] Using runtime version from GOOGLE_NODEJS_VERSION: 20.x.x
[builder] 2025/09/11 16:41:34 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json
[builder] ***** CACHE MISS: "nodejs"
[builder] Installing Node.js v20.19.5.
[builder] 2025/09/11 16:41:35 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/nodejs-20.19.5.tar.gz
[builder] === Node.js - Yarn (google.nodejs.yarn@2.1.0) ===
[builder] 2025/09/11 16:41:39 [DEBUG] GET https://registry.npmjs.org/yarn
[builder] ***** CACHE MISS: "yarn_engine"
[builder] Installing Yarn v1.22.22
[builder] 2025/09/11 16:41:40 [DEBUG] GET https://yarnpkg.com/downloads/1.22.22/yarn-v1.22.22.tar.gz
[builder] Setting environment variable PATH=/layers/google.nodejs.yarn/yarn_engine/bin:/layers/google.nodejs.runtime/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[builder] ***** CACHE MISS: "yarn_modules"
[builder] --------------------------------------------------------------------------------
[builder] Running "yarn install --non-interactive --prefer-offline --modules-folder=/layers/google.nodejs.yarn/yarn_modules/node_modules --frozen-lockfile (PATH=/layers/google.nodejs.yarn/yarn_engine/bin:/layers/google.nodejs.runtime/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/layers/google.nodejs.yarn/yarn_modules/node_modules/.bin)"
[builder] yarn install v1.22.22
[builder] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[builder] [1/4] Resolving packages...
[builder] [2/4] Fetching packages...
[builder] error Command failed.
[builder] Exit code: 128
[builder] Command: git
[builder] Arguments: ls-remote --tags --heads ssh://git@github.com/whiskeysockets/libsignal-node.git
[builder] Directory: /workspace
[builder] Output:
[builder] "ssh" -oBatchMode=yes: 1: ssh: not found
[builder] fatal: Could not read from remote repository.
[builder]
[builder] Please make sure you have the correct access rights
[builder] and the repository exists.
[builder] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder] Done "yarn install --non-interactive --prefer-offline --modules-fo..." (31.707493154s)
[builder] --------------------------------------------------------------------------------
[builder] failed to build: (error ID: 12c8ef4a):
[builder] yarn install v1.22.22
[builder] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[builder] [1/4] Resolving packages...
[builder] [2/4] Fetching packages...
[builder] error Command failed.
[builder] Exit code: 128
[builder] Command: git
[builder] Arguments: ls-remote --tags --heads ssh://git@github.com/whiskeysockets/libsignal-node.git
[builder] Directory: /workspace
[builder] Output:
[builder] "ssh" -oBatchMode=yes: 1: ssh: not found
[builder] fatal: Could not read from remote repository.
[builder]
[builder] Please make sure you have the correct access rights
[builder] and the repository exists.
[builder] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://cloud.google.com/docs/buildpacks/overview
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] --------------------------------------------------------------------------------
[builder] Timer: Builder ran for 37.05385656s and ended at 2025-09-11T16:42:12Z
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
time="2025-09-11T16:42:53.704Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2025-09-11T16:

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: b74c3b2b-ed24-4ee3-bf0a-21448fc61920