Assistant checkpoint: Fix deployment git dependency issue
Assistant generated file changes:
- package.json: Add resolutions to fix libsignal-node git dependency for deployment

---

User prompt:

Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying blob sha256:fc454e27c1c60562a35add6e2a13dcd2f674221ec85d4266e85594499abdaac2
Copying blob sha256:c7a1e0495b86ece89b90f07f89499da77bd90959345bc2aa99aec5ec94f79b5b
Copying blob sha256:1883854a1c2073510cb44d149993761e6dd869b53755813c64af78105caa9c36
Copying blob sha256:831b75755d45793a1d222f9195e6b8c5f317fae1193648478f2b299e69cadc88
Copying config sha256:456f7446368b903f920a982cf669f07aefc874b81ca986fb9e514c1285a98e2f
Writing manifest to image destination
Warning: PACK_VOLUME_KEY is unset; set this environment variable to a secret value to avoid creating a new volume cache on every build
===> ANALYZING
[analyzer] Image with name "imageblueprint" not found
===> DETECTING
[detector] Timer: Detector started at 2025-11-10T14:30:39Z
[detector] 3 of 5 buildpacks participating
[detector] google.nodejs.runtime    1.0.0
[detector] google.nodejs.yarn       2.1.0
[detector] google.utils.label-image 0.0.2
[detector] Timer: Detector ran for 60.573521ms and ended at 2025-11-10T14:30:39Z
===> RESTORING
time="2025-11-10T14:30:40Z" level=warning msg="IdleTracker: StateClosed transition by connection marked un-managed" X-Reference-Id=0xc00058e768
===> BUILDING
[builder] Timer: Builder started at 2025-11-10T14:30:41Z
[builder] === Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
[builder] Using runtime version from GOOGLE_NODEJS_VERSION: 20.x.x
[builder] 2025/11/10 14:30:41 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json
[builder] ***** CACHE MISS: "nodejs"
[builder] Installing Node.js v20.19.5.
[builder] 2025/11/10 14:30:42 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/nodejs-20.19.5.tar.gz
[builder] === Node.js - Yarn (google.nodejs.yarn@2.1.0) ===
[builder] 2025/11/10 14:30:43 [DEBUG] GET https://registry.npmjs.org/yarn
[builder] ***** CACHE MISS: "yarn_engine"
[builder] Installing Yarn v1.22.22
[builder] 2025/11/10 14:30:43 [DEBUG] GET https://yarnpkg.com/downloads/1.22.22/yarn-v1.22.22.tar.gz
[builder] Setting environment variable PATH=/layers/google.nodejs.yarn/yarn_engine/bin:/layers/google.nodejs.runtime/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[builder] ***** CACHE MISS: "yarn_modules"
[builder] --------------------------------------------------------------------------------
[builder] Running "yarn install --non-interactive --prefer-offline --modules-folder=/layers/google.nodejs.yarn/yarn_modules/node_modules --frozen-lockfile (PATH=/layers/google.nodejs.yarn/yarn_engine/bin:/layers/google.nodejs.runtime/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/layers/google.nodejs.yarn/yarn_modules/node_modules/.bin)"
[builder] yarn install v1.22.22
[builder] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[builder] [1/5] Validating package.json...
[builder] [2/5] Resolving packages...
[builder] [3/5] Fetching packages...
[builder] error Command failed.
[builder] Exit code: 128
[builder] Command: git
[builder] Arguments: ls-remote --tags --heads ssh://git@github.com/whiskeysockets/libsignal-node.git
[builder] Directory: /workspace
[builder] Output:
[builder] "ssh" -oBatchMode=yes: 1: ssh: not found
[builder] fatal: Could not read from remote repository.
[builder]
[builder] Please make sure you have the correct access rights
[builder] and the repository exists.
[builder] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder] Done "yarn install --non-interactive --prefer-offline --modules-fo..." (15.467772148s)
[builder] --------------------------------------------------------------------------------
[builder] yarn install v1.22.22
[builder] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[builder] [1/5] Validating package.json...
[builder] [2/5] Resolving packages...
[builder] [3/5] Fetching packages...
[builder] error Command failed.
[builder] Exit code: 128
[builder] Command: git
[builder] Arguments: ls-remote --tags --heads ssh://git@github.com/whiskeysockets/libsignal-node.git
[builder] Directory: /workspace
[builder] Output:
[builder] "ssh" -oBatchMode=yes: 1: ssh: not found
[builder] fatal: Could not read from remote repository.
[builder]
[builder] Please make sure you have the correct access rights
[builder] failed to build: (error ID: 12c8ef4a):
[builder] and the repository exists.
[builder] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://cloud.google.com/docs/buildpacks/overview
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] --------------------------------------------------------------------------------
[builder] Timer: Builder ran for 17.475611635s and ended at 2025-11-10T14:30:59Z
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
time="2025-11-10T14:31:15.106Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2025-11-10T14:31:15.106Z" level=info msg="not saving outputs - not main container" argo=true
Error: exit status 1

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: abd0c430-8e49-44df-a3cc-220e44bb5d76
Replit-Commit-Event-Id: 5e52d486-20bc-4357-8c10-c51b2f960426